# Generated by Django 3.2.7 on 2026-01-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_malpraticedetection_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='malpraticedetection',
            name='confidence_level',
            field=models.CharField(blank=True, choices=[('HIGH', 'High (>80%)'), ('MEDIUM', 'Medium (60-80%)'), ('LOW', 'Low (<60%)')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='malpraticedetection',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='AI confidence score (0-100)'),
        ),
        migrations.AddField(
            model_name='malpraticedetection',
            name='detection_count',
            field=models.IntegerField(default=1, help_text='Number of frames where malpractice was detected'),
        ),
        migrations.AlterField(
            model_name='lecturehall',
            name='building',
            field=models.CharField(choices=[('MAIN', 'Main Block'), ('NEW', 'New Block')], max_length=50),
        ),
    ]
