# Generated by Django 3.2.7 on 2026-01-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_malpraticedetection_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturehall',
            name='building',
            field=models.CharField(choices=[('MAIN', 'Main Block'), ('KE', 'Second Block'), ('PG', 'Third Block')], max_length=50),
        ),
    ]
