# Generated by Django 3.2.7 on 2026-01-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20260128_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malpraticedetection',
            name='confidence_level',
        ),
        migrations.RemoveField(
            model_name='malpraticedetection',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='malpraticedetection',
            name='detection_count',
        ),
    ]
